# Generated by Django 5.1 on 2024-08-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_de_jeu', models.CharField(max_length=255)),
                ('joueurs', models.ManyToManyField(related_name='tournois', to=settings.AUTH_USER_MODEL)),
                ('vainqueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournois_gagnes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
