# Generated by Django 5.1.1 on 2024-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_connect',
            field=models.BooleanField(default=False),
        ),
    ]
