# Generated by Django 5.1 on 2024-08-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_gameuser_friends_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
