# Generated by Django 5.1 on 2024-08-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userstats'),
        ('users', '0008_alter_userprofile_following'),
    ]

    operations = [
    ]
