# Generated by Django 5.1 on 2024-08-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0007_userstats_0008_alter_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
