# Generated by Django 5.1.1 on 2024-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_alter_usercustom_score_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='drunk_effect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='game_type',
            field=models.BooleanField(default=True),
        ),
    ]
