# Generated by Django 5.1.1 on 2024-10-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_usercustom_drunk_effect_usercustom_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='size_raquette',
            new_name='ball_speed',
        ),
        migrations.RenameField(
            model_name='usercustom',
            old_name='color_1',
            new_name='color_rackets',
        ),
        migrations.RenameField(
            model_name='usercustom',
            old_name='nb_balls',
            new_name='map',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='color_2',
        ),
    ]
