# Generated by Django 5.1.3 on 2024-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_rename_size_raquette_usercustom_ball_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='game_type',
            field=models.BooleanField(default=False),
        ),
    ]
