# Generated by Django 5.1 on 2024-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenfication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', to='authenfication.gameuser'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
