# Generated by Django 5.1 on 2024-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenfication', '0002_gameuser_avatar_gameuser_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to='authenfication.gameuser'),
        ),
    ]
