# Generated by Django 5.1.1 on 2024-10-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
