# Generated by Django 5.1.1 on 2024-10-21 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_last_called_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_called_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
